# ---------- Build Stage ----------
# Stage 1
FROM node:18-alpine AS build
WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client/ .

RUN npm run build


# ---------- Production Stage ----------
FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
